name: Bandit

on:
  # trigger on pushes to main branch
  push:
    branches: [main]
  # trigger on opening of a pull request to a main branch without merge conflicts
  pull_request:
    branches: [main]

jobs:
  analyze:
    runs-on: ubuntu-latest
    permissions:
      security-events: write
    steps:
      - name: Perform Bandit Analysis
        uses: shundor/python-bandit-scan@v1.0
        with: 
            path: "."
            level: high
            confidence: high
            exit_zero: true 
      
